In [32]:
'''4. Utilizando a biblioteca NumPy : 
a. Cria um array de números 1 com shape (8, 2) 
b. Cria um array de zeros com shape (5, 7) 
c. Subtraia o novo array de outro com dados aleatórios e armazene o numa variável 
chamada subarray 
d. Calcula a média dos valores do array subarray '''

'4. Utilizando a biblioteca NumPy : \na. Cria um array de números 1 com shape (8, 2) \nb. Cria um array de zeros com shape (5, 7) \nc. Subtraia o novo array de outro com dados aleatórios e armazene o numa variável \nchamada subarray \nd. Calcula a média dos valores do array subarray '

In [ ]:
# 4. Utilizando a biblioteca NumPy : 

import numpy        # Import o NumPy
import numpy as np


In [ ]:
# a. Cria um array de números 1 com shape (8, 2).

obj = numpy.ones((8,2))
print(obj)
print(obj.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
(8, 2)


In [ ]:
# b. Cria um array de zeros com shape (5, 7).

obj = numpy.zeros((5,7))
print(obj)
print(obj.shape)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
(5, 7)


In [33]:
# c. Subtraia o novo array de outro com dados aleatórios e armazene o numa variável 
#    chamada subarray.

#import numpy as np

# Criar um array random_array com valores aleatórios
random_array = np.random.randint(1, 7, size=(2, 4))
print(f"Array dados aleatórios:\n", random_array)

# Array obj com zeros (5, 7), alenea b
#obj = np.zeros((5, 7))
print(f"Array obj (inicializado com zeros):\n", obj)

# Verificar se os arrays são iguais
if obj.shape != random_array.shape:
    print(f"As formas são diferentes: {random_array.shape} vs {obj.shape}")
    
    # Comparar arrays
    if obj.shape[0] > random_array.shape[0]:
        # Se obj tem mais linhas, aumentamos o random_array com zeros
        random_array = np.pad(random_array, ((0, obj.shape[0] - random_array.shape[0]), (0, 0)), mode='constant', constant_values=0)
        print(f"random_array após preenchimento com zeros para (5, 4):\n", random_array)
    elif obj.shape[0] < random_array.shape[0]:
        # Se random_array tem mais linhas, cortamos random_array
        random_array = random_array[:obj.shape[0], :]
        print(f"random_array após corte para (5, 4):\n", random_array)
    
    if obj.shape[1] > random_array.shape[1]:
        # Se obj tem mais colunas, aumentamos random_array
        random_array = np.hstack([random_array, np.zeros((random_array.shape[0], obj.shape[1] - random_array.shape[1]))])
        print(f"random_array após expansão para (5, 7):\n", random_array)
    elif obj.shape[1] < random_array.shape[1]:
        # Se random_array tem mais colunas, cortamos random_array
        random_array = random_array[:, :obj.shape[1]]
        print(f"random_array após corte para (5, 7):\n", random_array)

# Agora j´podemos subtrair
subarray = obj - random_array
print("\nResultado da subtração, array subarray:\n", subarray)

Array dados aleatórios:
 [[6 2 3 2]
 [4 4 2 1]]
Array obj (inicializado com zeros):
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
As formas são diferentes: (2, 4) vs (5, 7)
random_array após preenchimento com zeros para (5, 4):
 [[6 2 3 2]
 [4 4 2 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
random_array após expansão para (5, 7):
 [[6. 2. 3. 2. 0. 0. 0.]
 [4. 4. 2. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

Resultado da subtração, array subarray:
 [[-6. -2. -3. -2.  0.  0.  0.]
 [-4. -4. -2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [34]:
#d. Calcula a média dos valores do array subarray

# Calculo média de valores de subarray
media_subarray = np.mean(subarray)
print(f"Média dos valores de subarray: {media_subarray}")

Média dos valores de subarray: -0.6857142857142857
